///////////////////////////////////////////////////////////////////////////////
// FILE:          WidefieldGpuD3D11.h
// PROJECT:       insiliscope
// SUBSYSTEM:     Simulation engine (no MMDevice dependency)
//-----------------------------------------------------------------------------
// DESCRIPTION:   The WideField GPU host of the adapter: runs the kernels of
//                WidefieldGpu.wgsl (HLSL generated by tools/gen_wf_gpu.mjs,
//                WidefieldGpuHlsl.inc) on Direct3D 11 -- the same algorithm as
//                the viewer's web/wf_gpu.js; keep the two in step.
//
//                As a WidefieldAccelerator it takes a scene's focus work: plane
//                spectra (resident as fp16 pairs, keyed across jobs), the
//                re-pairing with the kernel spectra, the images. RenderFrames
//                then makes whole stack batches on the GPU: dyes from the
//                images, background, the camera noise chain (the counter-based
//                stream of SMLMCounterRng.h), read back as ADU.
//
//                Create() rejects software adapters (as GpuSimD3D11) and runs a
//                self-check -- a synthetic scene's images against the CPU's
//                (<= 1e-3 rms) -- so a driver or compiler that gets the kernels
//                wrong leaves the CPU path in charge. Windows only; elsewhere
//                Create() returns nullptr. One instance per thread.
//
// LICENSE:       BSD-3-Clause (see LICENSE at the repository root)

#pragma once

#include "SMLMNoise.h"
#include "WidefieldRender.h"

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace sim {

class WidefieldGpuD3D11 : public WidefieldAccelerator
{
public:
   // nullptr (info = why) if there is no usable hardware device, a kernel
   // does not compile, or the self-check fails; info = the adapter otherwise.
   static std::unique_ptr<WidefieldGpuD3D11> Create(std::string& info);
   ~WidefieldGpuD3D11() override;

   bool HasPlane(unsigned long long geometry, unsigned long long key) const override;
   bool Images(const WidefieldGpuJob& job, std::vector<std::vector<float>>& out, std::string& err) override;

   // Per-pixel frame inputs (width x height; empty maps = the scalar from
   // cam): offset ADU, gain photons/ADU, read noise e-, background photons
   // before the per-frame fade (empty = flatBg).
   bool SetFrameStatic(unsigned width, unsigned height, const std::vector<float>& offset,
                       const std::vector<float>& gain, const std::vector<float>& readNoise,
                       const std::vector<float>& background, double flatBg, const CameraNoiseParams& cam,
                       std::string& err);
   // Frames k = 0..n-1: images (the scene's, for its focus) with bleach
   // coefficients coef[k], background x bgScale[k], noise keyed by
   // (seed, frames[k]); outs[k] receives width x height ADU.
   bool RenderFrames(const WidefieldImages& images, const std::vector<std::vector<double>>& coef,
                     const std::vector<uint32_t>& frames, const std::vector<double>& bgScale,
                     const CameraNoiseParams& cam, uint32_t seed, const std::vector<std::vector<uint16_t>*>& outs,
                     std::string& err);

private:
   bool ImagesImpl(const WidefieldGpuJob& job, std::vector<std::vector<float>>& out, std::string& err);
   struct Impl;
   explicit WidefieldGpuD3D11(std::unique_ptr<Impl> impl);
   std::unique_ptr<Impl> impl_;
};

} // namespace sim
