#!/usr/bin/env node
// Wraps the viewer's single-file WASM build (and the WideField GPU kernels' WGSL) (build/wasm/cli/insiliscope_scope_single.js:
// the core's C ABI + isc_scope_movie, the adapter's render code; WASM inlined as base64) into web/insiliscope_module.js, as source TEXT the
// viewer can evaluate on the main thread and hand to its Web Workers (a page
// opened from file:// cannot fetch() or importScripts() a sibling file).
//
//   node tools/embed_web_module.mjs            # (re)write web/insiliscope_module.js
//   node tools/embed_web_module.mjs --check    # exit 1 if it is stale
//
// Build first: source ~/emsdk/emsdk_env.sh && cmake --preset wasm && cmake --build --preset wasm
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'build/wasm/cli/insiliscope_scope_single.js');
const OUT = path.join(ROOT, 'web/insiliscope_module.js');
const WGSL = path.join(ROOT, 'adapter/inSiliScope/Simulation/WidefieldGpu.wgsl');
const check = process.argv.includes('--check');

const mod = fs.readFileSync(SRC, 'utf8');
if (/[^\x09\x0a\x0d\x20-\x7e]/.test(mod)) throw new Error('module is not plain ASCII (SINGLE_FILE_BINARY_ENCODE=0?)');
const abi = /#define ISC_ABI_VERSION (\d+)/.exec(fs.readFileSync(path.join(ROOT, 'core/include/insiliscope/insiliscope.h'), 'utf8'))[1];
const cache = fs.readFileSync(path.join(ROOT, 'build/wasm/CMakeCache.txt'), 'utf8');
const tc = (/CMAKE_TOOLCHAIN_FILE:\w+=(.+)/.exec(cache) || [])[1];
const verFile = tc && path.resolve(path.dirname(tc.trim()), '../../../emscripten-version.txt');
const emver = verFile && fs.existsSync(verFile) ? fs.readFileSync(verFile, 'utf8').trim().replace(/"/g, '') : 'unknown';
const sha = crypto.createHash('sha256').update(mod).digest('hex');

const text =
`// GENERATED by tools/embed_web_module.mjs from the insiliscope_scope_web target -- do not edit.
// insiliscope core (C ABI ${abi}) + scope movie, Emscripten ${emver}, sha256(module) ${sha}
// Rebuild: cmake --preset wasm && cmake --build --preset wasm && node tools/embed_web_module.mjs
// The module as source text (WASM inlined as base64): evaluating it defines
// createInsiliscope(); the viewer does that on the main thread and in each worker.
self.ISC_MODULE_SRC = ${JSON.stringify(mod)};
// The WideField GPU kernels (adapter/inSiliScope/Simulation/WidefieldGpu.wgsl), for web/wf_gpu.js.
self.ISC_WF_WGSL = ${JSON.stringify(fs.readFileSync(WGSL, 'utf8'))};
`;

if (check) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== text) { console.error(`${path.relative(ROOT, OUT)} is stale: run node tools/embed_web_module.mjs`); process.exit(1); }
  console.log(`${path.relative(ROOT, OUT)} is up to date (sha256 ${sha.slice(0, 12)})`);
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)}: ${(text.length / 1024).toFixed(1)} KB, ABI ${abi}, sha256 ${sha.slice(0, 12)}`);
}
