"""Writes docs/mm-properties.md: every Micro-Manager device and property of the inSiliScope adapter, by tier.

Generated, never hand-edited: the rows come from the adapter's property registry (Registry/PropertyTable.cpp, exported
by the Test row Renderer.Test_WriteRegistryTo), the device types, descriptions and pre-init properties from the loaded
devices (pymmcore-plus), so ADAPTER_DIR must point at a built adapter.

  ADAPTER_DIR=<dll dir> python tools/gen_property_reference.py          # write docs/mm-properties.md
  ADAPTER_DIR=<dll dir> python tools/gen_property_reference.py --check  # fail if it is out of date
"""

import json
import os
import sys
import tempfile
from pathlib import Path

os.environ["ISC_TEST"] = "1"   # the Test rows too (the export row is one; listed in their own section)
sys.path.insert(0, str(Path(__file__).resolve().parent))
from isc_mm import ALL_DEVICES, HUB, search_paths  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "mm-properties.md"
TIERS = ("Basic", "Advanced", "Expert")
# Micro-Manager's own properties (its GUI depends on these names); not part of the registry.
STANDARD = {"Name", "Description", "HubID", "State", "Label", "Position", "Exposure", "Binning", "PixelType",
            "CameraName", "CameraID", "TransposeMirrorX", "TransposeMirrorY", "TransposeXY", "TransposeCorrection"}
TYPES = {"CameraDevice": "Camera", "StageDevice": "Stage", "XYStageDevice": "XY stage", "StateDevice": "State",
         "ShutterDevice": "Shutter", "MagnifierDevice": "Magnifier", "GenericDevice": "Generic", "HubDevice": "Hub"}


def cell(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def read_adapter():
    from pymmcore_plus import CMMCorePlus

    core = CMMCorePlus()
    core.setDeviceAdapterSearchPaths(search_paths())
    # The devices each Detail offers (the hub's device list).
    offered = {}
    for tier in TIERS:
        core.loadDevice(HUB, "inSiliScope", "inSiliScope")
        core.setProperty(HUB, "Detail", tier)
        core.initializeDevice(HUB)
        offered[tier] = set(core.getInstalledDevices(HUB))
        core.unloadAllDevices()
    core.loadDevice(HUB, "inSiliScope", "inSiliScope")
    for d in ALL_DEVICES:
        core.loadDevice(d, "inSiliScope", d)
        core.setParentLabel(d, HUB)
    # The pre-init defaults, before Detail is set.
    pre = {d: {p: (core.getProperty(d, p), list(core.getAllowedPropertyValues(d, p)))
               for p in core.getDevicePropertyNames(d) if core.isPropertyPreInit(d, p)} for d in [HUB] + ALL_DEVICES}
    core.setProperty(HUB, "Detail", "Expert")
    core.initializeAllDevices()
    devices = {}
    for d in [HUB] + ALL_DEVICES:
        dtype = str(core.getDeviceType(d)).split(".")[-1]
        tier = next((t for t in TIERS if d in offered[t]), "Basic")   # the hub itself: always
        devices[d] = {"type": TYPES.get(dtype, dtype), "tier": tier,
                      "description": core.getProperty(d, "Description")
                      if core.hasProperty(d, "Description") else "",
                      "props": set(core.getDevicePropertyNames(d))}
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "registry.json")
        core.setProperty("Renderer", "Test_WriteRegistryTo", path)
        rows = json.loads(Path(path).read_text(encoding="utf-8"))
    core.unloadAllDevices()
    return devices, pre, rows


def values(r):
    if r.get("choices"):
        return ", ".join(f"`{c}`" for c in r["choices"])
    if "lo" in r:
        return f"{r['lo']} .. {r['hi']}"
    return ""


def build(devices, pre, rows):
    L = []
    w = L.append
    w("# Micro-Manager devices and properties")
    w("")
    w("<!-- Generated by tools/gen_property_reference.py from the adapter's property registry -- do not edit. -->")
    w("")
    w("The inSiliScope adapter is a hub (`inSiliScope`) with one device per part of the microscope. Every property has a")
    w("**tier**: the hub's pre-init `Detail` (Basic, Advanced or Expert) decides which tiers a session shows; a property")
    w("above it is not created and keeps its default. The shipped configurations `adapter/inSiliScope/config/"
      "inSiliScope_{Basic,Advanced,Expert}.cfg`")
    w("load the devices with their config groups (Channel, Objective, Camera, Quality, Drift, Specimen) and pixel-size")
    w("calibrations. Where a new property belongs, and the rules behind the tiers: `spec/MM_DEVICES.md` in the repository.")
    w("Micro-Manager's own properties (`Exposure`, `Binning`, `State`, `Label`, `Position`, ...) are not listed.")
    w("")
    w("| Device | Type | Tier | What it is |")
    w("|---|---|---|---|")
    for d, info in devices.items():
        w(f"| `{d}` | {info['type']} | {info['tier']} | {cell(info['description'])} |")
    w("")
    by_dev = {}
    for r in rows:
        by_dev.setdefault(r["device"], []).append(r)
    test_rows = []
    for d, info in devices.items():
        listed = []
        for p, (val, allowed) in sorted(pre.get(d, {}).items()):
            if p in STANDARD:
                continue
            listed.append(f"| `{p}` | pre-init | {cell(val)} | {', '.join(f'`{a}`' for a in allowed)} | "
                          f"set before the devices initialize |")
        for t in TIERS:
            for r in by_dev.get(d, []):
                if r["tier"] != t or r["name"] in pre.get(d, {}):
                    continue
                ro = " (read-only)" if r["readOnly"] else ""
                listed.append(f"| `{r['name']}` | {t}{ro} | {cell(r.get('value', ''))} | {cell(values(r))} | "
                              f"{cell(r['help'])} |")
        test_rows += [r for r in by_dev.get(d, []) if r["tier"] == "Test"]
        if not listed:
            continue
        w(f"## {d}")
        w("")
        if info["description"]:
            w(f"{info['description']}.")
            w("")
        w("| Property | Tier | Default | Values | Description |")
        w("|---|---|---|---|---|")
        L.extend(listed)
        w("")
    if test_rows:
        w("## For tests only")
        w("")
        w("Created only when the process has the environment variable `ISC_TEST=1` (the test scripts in `tools/`), never")
        w("by `Detail`: the precomputed, seeded stack the reproducibility checks use, and tooling hooks.")
        w("")
        w("| Device | Property | Description |")
        w("|---|---|---|")
        for r in test_rows:
            w(f"| `{r['device']}` | `{r['name']}` | {cell(r['help'])} |")
        w("")
    return "\n".join(L)


def main():
    devices, pre, rows = read_adapter()
    # Test rows the camera creates itself (not in the registry): listed from MM.
    reg = {(r["device"], r["name"]) for r in rows}
    for d, info in devices.items():
        for p in sorted(info["props"]):
            if p.startswith("Test_") and (d, p) not in reg:
                rows.append({"device": d, "name": p, "tier": "Test", "readOnly": False, "help": ""})
    text = build(devices, pre, rows)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("docs/mm-properties.md is out of date (run tools/gen_property_reference.py)")
        print("docs/mm-properties.md up to date")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} registry rows)")


if __name__ == "__main__":
    main()
