#!/usr/bin/env node
// Generates the Direct3D 11 HLSL of the WideField GPU kernels from their one
// source, adapter/inSiliScope/Simulation/WidefieldGpu.wgsl, with naga
// (`cargo install naga-cli`): every "//// kernel <name>" section, with the
// "//// common" section prepended, is validated and translated on its own
// (Shader Model 5.0, unchecked indexing -- the kernels bound-check
// themselves) into adapter/inSiliScope/Simulation/WidefieldGpuHlsl.inc.
// The viewer takes the WGSL itself (tools/embed_web_module.mjs embeds it).
//
//   node tools/gen_wf_gpu.mjs            # (re)write the .inc
//   node tools/gen_wf_gpu.mjs --check    # exit 1 if it is stale (needs naga)
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'adapter/inSiliScope/Simulation/WidefieldGpu.wgsl');
const OUT = path.join(ROOT, 'adapter/inSiliScope/Simulation/WidefieldGpuHlsl.inc');
const check = process.argv.includes('--check');

export function wfKernels(text) {
  const parts = text.split(/^\/\/\/\/ /m);
  let common = '';
  const kernels = [];
  for (const p of parts.slice(1)) {
    const nl = p.indexOf('\n');
    const head = p.slice(0, nl).trim(), body = p.slice(nl + 1);
    if (head === 'common') common = body;
    else if (head.startsWith('kernel ')) kernels.push({ name: head.slice(7).trim(), body });
  }
  return kernels.map(k => ({ name: k.name, wgsl: common + '\n' + k.body }));
}

function toHlsl(k, tmp) {
  const inp = path.join(tmp, k.name + '.wgsl'), out = path.join(tmp, k.name + '.hlsl');
  fs.writeFileSync(inp, k.wgsl);
  execFileSync('naga', ['--index-bounds-check-policy', 'Unchecked', '--shader-model', '50', inp, out], { stdio: 'pipe' });
  let h = fs.readFileSync(out, 'utf8');
  // naga zero-fills workgroup memory from one thread (WGSL's semantics); the
  // kernels write every element they read, so drop it.
  h = h.replace(/ {4}if \(local_invocation_index == 0\) \{\n\s*buf = \(float2\[2048\]\)0;\n\s*\}\n\s*GroupMemoryBarrierWithGroupSync\(\);\n/, '');
  // A cbuffer named like its member confuses some HLSL compilers (vkd3d).
  h = h.replace(/cbuffer P : register\(b0\) \{ (\w+) P; \}/, 'cbuffer ParamsCB : register(b0) { $1 P; }');
  return h;
}

// MSVC caps one string literal at ~16 KB: split into adjacent pieces.
function cString(s) {
  const pieces = [];
  for (let i = 0; i < s.length; i += 12000) pieces.push(s.slice(i, i + 12000));
  return pieces.map(p => `R"HLSL(${p})HLSL"`).join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const wgsl = fs.readFileSync(SRC, 'utf8');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'wfgpu-'));
  let body = '';
  for (const k of wfKernels(wgsl)) body += `   {"${k.name}",\n${cString(toHlsl(k, tmp))}},\n`;
  fs.rmSync(tmp, { recursive: true, force: true });
  const text =
`// GENERATED by tools/gen_wf_gpu.mjs from WidefieldGpu.wgsl (naga, Shader Model 5.0) -- do not edit.
// { entry point, HLSL source } per kernel; compiled at run time with D3DCompile (cs_5_0).
static const struct { const char* name; const char* hlsl; } kWfGpuKernels[] = {
${body}};
`;
  if (check) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (cur !== text) { console.error(`${path.relative(ROOT, OUT)} is stale: run node tools/gen_wf_gpu.mjs`); process.exit(1); }
    console.log(`${path.relative(ROOT, OUT)} is up to date`);
  } else {
    fs.writeFileSync(OUT, text);
    console.log(`wrote ${path.relative(ROOT, OUT)}: ${wfKernels(wgsl).length} kernels, ${(text.length / 1024).toFixed(1)} KB`);
  }
}
