"""Regenerate core/src/jsmath_fdlibm.cpp from V8's src/base/ieee754.cc.

Usage: python tools/gen_jsmath.py [V8_TAG]

V8_TAG defaults to the V8 of the Node used for the golden vectors
(`node -p process.versions.v8`, trimmed to 4 components). The bodies are
copied verbatim: bit-exactness with JS Math.* depends on them.
"""
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'core' / 'src' / 'jsmath_fdlibm.cpp'


def v8_tag():
    if len(sys.argv) > 1:
        return sys.argv[1]
    v = subprocess.check_output(['node', '-p', 'process.versions.v8'], text=True, shell=True).strip()
    return '.'.join(v.split('-')[0].split('.')[:4])


def main():
    tag = v8_tag()
    url = f'https://raw.githubusercontent.com/v8/v8/{tag}/src/base/ieee754.cc'
    src = urllib.request.urlopen(url).read().decode('utf-8').split('\n')

    def find(prefix):
        return next(i for i, l in enumerate(src) if l.startswith(prefix))

    def body(i):  # from line i to the first column-0 "}"
        j = i
        while src[j] != '}':
            j += 1
        return [l for l in src[i:j + 1] if l != '#endif']

    def doc(i):  # the /* ... */ block directly above line i (skipping #if lines)
        j = i - 1
        while src[j].startswith('#'):
            j -= 1
        if not src[j].strip().endswith('*/'):
            return []
        k = j
        while not src[k].lstrip().startswith('/*'):
            k -= 1
        return src[k:j + 1]

    license_end = find('#include')          # Sun + V8 notice precedes the includes
    anon_start = find('namespace {') + 1
    helpers_end = find('double __kernel_tan(')  # everything the used functions need

    out = src[:license_end]
    out += [
        '//',
        f'// GENERATED by tools/gen_jsmath.py from V8 {tag} src/base/ieee754.cc -- do not edit.',
        '// sin, cos, atan, atan2, exp, log (+ kernels), verbatim apart from the V8',
        '// macro/bit_cast plumbing: exactly what V8 runs for Math.sin/cos/atan/atan2/',
        '// exp/log (fdlibm; Node is not built with V8_USE_LIBM_TRIG_FUNCTIONS).',
        '',
        '#include "jsmath.h"',
        '',
        '#include <cmath>',
        '#include <cstdint>',
        '#include <cstring>',
        '#include <limits>',
        '#include <type_traits>',
        '',
        'namespace isc {',
        'namespace jsm {',
        '',
        'namespace {',
        '',
        'template <class To, class From>',
        'inline To bit_cast_(const From& f) { To t; std::memcpy(&t, &f, sizeof t); return t; }',
        '// src/base/overflowing-math.h equivalents',
        'template <class T> inline T AddWithWraparound(T a, T b) {',
        '  using U = typename std::make_unsigned<T>::type;',
        '  return static_cast<T>(static_cast<U>(a) + static_cast<U>(b)); }',
        'template <class T> inline T SubWithWraparound(T a, T b) {',
        '  using U = typename std::make_unsigned<T>::type;',
        '  return static_cast<T>(static_cast<U>(a) - static_cast<U>(b)); }',
        'template <class T> inline T NegateWithWraparound(T a) {',
        '  if (a == std::numeric_limits<T>::min()) return a;',
        '  return -a; }',
        '#define V8_WARN_UNUSED_RESULT',
        '#define V8_INLINE inline',
        '#ifdef _MSC_VER',
        '#pragma warning(disable : 4723 4244)',
        '#endif',
    ]
    helpers = [l for l in src[anon_start:helpers_end] if 'V8_CC_MSVC' not in l]
    # drop the now-empty MSVC pragma block copied from the original
    helpers = [l for l in helpers if l not in ('#pragma warning(disable : 4723)', '#endif')]
    out += [l.replace('base::bit_cast', 'bit_cast_') for l in helpers]
    out += ['}  // namespace', '']
    for sig in ('double atan(double x) {', 'double atan2(double y, double x) {',
                'double exp(double x) {', 'double log(double x) {'):
        i = find(sig)
        out += doc(i) + body(i) + ['']
    for name in ('cos', 'sin'):
        i = find(f'double {name}(double x) {{')  # the non-libm branch of the #if
        out += doc(i - 2) + body(i) + ['']
    out += ['}  // namespace jsm', '}  // namespace isc', '']
    OUT.write_text('\n'.join(out), encoding='utf-8', newline='\n')
    print(f'wrote {OUT.relative_to(ROOT)} from V8 {tag}')


if __name__ == '__main__':
    main()
