// The WideField GPU host of the viewer (WebGPU): runs the kernels of
// adapter/inSiliScope/Simulation/WidefieldGpu.wgsl (embedded as
// self.ISC_WF_WGSL by tools/embed_web_module.mjs) on a WidefieldGpuJob read
// from the WASM module (isc_wf_job and its getters, cli/scope_wasm.cpp), and
// returns the channel images the scene then renders frames from. The same
// kernels run in the adapter on Direct3D 11 (Simulation/WidefieldGpuD3D11.cpp,
// HLSL generated by tools/gen_wf_gpu.mjs): keep the two hosts in step.
//
// Plane spectra stay on the GPU (fp16 pairs, scaled by 1 / sum |values|),
// keyed by (channel weights, world plane) within one job geometry, so a new
// job at another focus of the same scene only re-pairs them.
//
// Self-contained (stringified into the viewer's workers): defines
// self.IscWfGpu = { create(wgsl) -> Promise<host|null>, jobFromModule(M, h) }.
function iscWfGpuDefine() {
  const NONE = 0xffffffff;

  function kernelSources(text) {
    const parts = text.split(/^\/\/\/\/ /m);
    let common = '';
    const out = {};
    for (const p of parts.slice(1)) {
      const nl = p.indexOf('\n');
      const head = p.slice(0, nl).trim(), body = p.slice(nl + 1);
      if (head === 'common') common = body;
      else if (head.startsWith('kernel ')) out[head.slice(7).trim()] = body;
    }
    for (const k of Object.keys(out)) out[k] = common + '\n' + out[k];
    return out;
  }

  const f32bits = (() => { const f = new Float32Array(1), u = new Uint32Array(f.buffer); return v => { f[0] = v; return u[0]; }; })();

  class Host {
    constructor(device, wgsl) {
      this.device = device;
      this.pipes = {};
      const src = kernelSources(wgsl);
      for (const [name, code] of Object.entries(src)) {
        const module = device.createShaderModule({ code });
        this.pipes[name] = device.createComputePipeline({ layout: 'auto', compute: { module, entryPoint: name } });
      }
      this.geometry = null;
      this.planes = new Map(); // key -> { slot, used }
      this.kernels = new Map(); // p -> kslot
      this.clock = 0;
      this.maxBinding = Math.min(device.limits.maxStorageBufferBindingSize, device.limits.maxBufferSize);
      this.lost = null;
      device.lost.then(i => { this.lost = i.message || 'device lost'; });
    }

    // allowFallback: accept a software adapter (tests; it is slower than the
    // CPU path otherwise, as WARP is for the adapter's D3D11 path).
    static async create(wgsl, allowFallback = false) {
      const gpu = self.navigator && self.navigator.gpu;
      if (!gpu || !wgsl) return null;
      const adapter = await gpu.requestAdapter({ powerPreference: 'high-performance' });
      if (!adapter) return null;
      const fallback = adapter.isFallbackAdapter || (adapter.info && (adapter.info.isFallbackAdapter ||
        /swiftshader|llvmpipe|basic render/i.test(`${adapter.info.architecture} ${adapter.info.description}`)));
      if (fallback && !allowFallback) return null;
      const lim = adapter.limits;
      const device = await adapter.requestDevice({
        requiredLimits: {
          maxStorageBufferBindingSize: lim.maxStorageBufferBindingSize,
          maxBufferSize: lim.maxBufferSize,
          maxComputeWorkgroupStorageSize: Math.max(16384, Math.min(32768, lim.maxComputeWorkgroupStorageSize)),
          maxStorageBuffersPerShaderStage: Math.min(8, lim.maxStorageBuffersPerShaderStage),
        },
      });
      const h = new Host(device, wgsl);
      h.adapterInfo = adapter.info ? `${adapter.info.vendor} ${adapter.info.architecture} ${adapter.info.description}`.trim() : 'WebGPU';
      return h;
    }

    buffer(size, usage) {
      return this.device.createBuffer({ size: Math.max(16, Math.ceil(size / 4) * 4), usage });
    }
    storage(size) {
      return this.buffer(size, GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC);
    }
    upload(arr) {
      const b = this.buffer(arr.byteLength, GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST);
      this.device.queue.writeBuffer(b, 0, arr.buffer, arr.byteOffset, arr.byteLength);
      return b;
    }
    uniform(u32s) {
      const a = new Uint32Array(Math.ceil(u32s.length / 4) * 4);
      a.set(u32s);
      const b = this.buffer(a.byteLength, GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST);
      this.device.queue.writeBuffer(b, 0, a);
      return b;
    }
    // One dispatch: bindings [uniform, ...storage] in binding order.
    dispatch(enc, name, buffers, x, y = 1, z = 1) {
      const pipe = this.pipes[name];
      const bg = this.device.createBindGroup({
        layout: pipe.getBindGroupLayout(0),
        entries: buffers.map((b, i) => ({ binding: i, resource: { buffer: b } })),
      });
      const pass = enc.beginComputePass();
      pass.setPipeline(pipe);
      pass.setBindGroup(0, bg);
      pass.dispatchWorkgroups(x, y, z);
      pass.end();
    }
    // 1D count of workgroups of 256 as (x, y) within the 65535 limit.
    grid256(count) {
      const groups = Math.max(1, Math.ceil(count / 256));
      const x = Math.min(groups, 65535), y = Math.ceil(groups / x);
      return [x, y, x * 256];
    }

    reset(job) {
      const W = job.NX / 2 + 1, SS = W * job.NY;
      this.geometry = `${job.geometry}:${job.NX}x${job.NY}:${job.nx}x${job.ny}`;
      this.NX = job.NX; this.NY = job.NY; this.W = W; this.SS = SS; this.PS = job.NX * job.NY;
      for (const b of [this.spec16, this.kspec, this.work, this.tw]) if (b) b.destroy();
      // Resident fp16 plane spectra: as many slots as one binding allows (at most 512 MB).
      this.slotCap = Math.max(4, Math.floor(Math.min(this.maxBinding, 512 << 20) / (SS * 4)));
      this.spec16 = this.storage(this.slotCap * SS * 4);
      this.freeSlots = [];
      for (let i = this.slotCap - 1; i >= 0; i--) this.freeSlots.push(i);
      this.planes.clear();
      this.kernels.clear();
      this.kspec = null; this.kcap = 0;
      // Work grids: pairs of planes / channels.
      this.pairCap = Math.max(1, Math.min(32, Math.floor(Math.min(this.maxBinding, 256 << 20) / (this.PS * 8))));
      this.work = this.storage(this.pairCap * this.PS * 8);
      // Twiddles exp(-2 pi i k / n): NX's at 0, NY's at NX / 2.
      const tw = new Float32Array(job.NX + job.NY);
      for (const [n, off] of [[job.NX, 0], [job.NY, job.NX / 2]])
        for (let k = 0; k < n / 2; k++) {
          const a = -2 * Math.PI * k / n;
          tw[2 * (off + k)] = Math.cos(a); tw[2 * (off + k) + 1] = Math.sin(a);
        }
      this.tw = this.upload(tw);
    }

    // FFT of `pairs` complex grids in this.work: rows then columns.
    fft2(enc, pairs, inverse, temps) {
      const NX = this.NX, NY = this.NY, lx = Math.log2(NX), ly = Math.log2(NY);
      const rows = this.uniform([NX, lx, 1, NX, this.PS, inverse, 0, 0]);
      const cols = this.uniform([NY, ly, NX, 1, this.PS, inverse, NX / 2, 0]);
      temps.push(rows, cols);
      this.dispatch(enc, 'wf_fft', [rows, this.work, this.tw], NY, 1, pairs);
      this.dispatch(enc, 'wf_fft', [cols, this.work, this.tw], NX, 1, pairs);
    }

    ensureKernels(job) {
      const missing = job.kernels.filter(k => !this.kernels.has(k.p));
      if (!missing.length) return;
      const need = this.kernels.size + missing.length, bytes = this.SS * 8;
      if (need > this.kcap) {
        const cap = Math.max(need, Math.min(Math.floor(this.maxBinding / bytes), 2 * this.kcap || 16));
        if (cap < need) throw new Error('too many PSF planes for one GPU binding');
        const nb = this.storage(cap * bytes);
        if (this.kspec) {
          const enc = this.device.createCommandEncoder();
          enc.copyBufferToBuffer(this.kspec, 0, nb, 0, this.kernels.size * bytes);
          this.device.queue.submit([enc.finish()]);
          this.kspec.destroy();
        }
        this.kspec = nb; this.kcap = cap;
      }
      for (const k of missing) {
        const slot = this.kernels.size;
        this.kernels.set(k.p, slot);
        this.device.queue.writeBuffer(this.kspec, slot * bytes, k.spec.buffer, k.spec.byteOffset, bytes);
      }
    }

    // Plane spectra the job needs and the GPU lacks: pairs of planes per
    // grid, batches of pairCap grids.
    ensurePlanes(job, needed) {
      const stamp = ++this.clock;
      for (const key of needed) { const e = this.planes.get(key); if (e) e.used = stamp; }
      const todo = job.planes.filter(p => !this.planes.has(p.key) && p.cells.length);
      // Slots, evicting the least recently used planes this job does not use.
      if (todo.length > this.freeSlots.length) {
        const victims = [...this.planes.entries()].filter(([, e]) => e.used < stamp).sort((a, b) => a[1].used - b[1].used);
        while (todo.length > this.freeSlots.length && victims.length) {
          const [key, e] = victims.shift();
          this.planes.delete(key);
          this.freeSlots.push(e.slot);
        }
        if (todo.length > this.freeSlots.length) throw new Error('GPU plane spectra do not fit');
      }
      for (const p of todo) this.planes.set(p.key, { slot: this.freeSlots.pop(), used: stamp, scale: p.absSum });
      for (let b0 = 0; b0 < todo.length; b0 += 2 * this.pairCap) {
        const batch = todo.slice(b0, b0 + 2 * this.pairCap), pairs = Math.ceil(batch.length / 2);
        let n = 0;
        for (const p of batch) n += p.cells.length;
        const entries = new Uint32Array(4 * n), slots = new Uint32Array(4 * pairs);
        let e = 0;
        batch.forEach((p, i) => {
          const pair = i >> 1, comp = i & 1;
          for (let j = 0; j < p.cells.length; j++, e++) {
            entries[4 * e] = pair; entries[4 * e + 1] = p.cells[j];
            entries[4 * e + 2] = f32bits(p.values[j]); entries[4 * e + 3] = comp;
          }
          slots[4 * pair + comp] = this.planes.get(p.key).slot;
          slots[4 * pair + 2 + comp] = f32bits(1 / p.absSum);
          if (comp === 0) slots[4 * pair + 1] = NONE;
        });
        const temps = [];
        const enc = this.device.createCommandEncoder();
        const [cx, cy, cl] = this.grid256(pairs * this.PS);
        const clr = this.uniform([pairs * this.PS, cl, 0, 0]);
        this.dispatch(enc, 'wf_clear', [clr, this.work], cx, cy);
        const eb = this.upload(entries);
        const [sx, sy, sl] = this.grid256(n);
        const sct = this.uniform([n, job.nx, this.NX, this.PS, sl, 0, 0, 0]);
        this.dispatch(enc, 'wf_scatter', [sct, eb, this.work], sx, sy);
        this.fft2(enc, pairs, 0, temps);
        const sb = this.upload(slots);
        const sp = this.uniform([this.NX, this.NY, this.W, this.SS, this.PS, pairs, 0, 0]);
        this.dispatch(enc, 'wf_split', [sp, this.work, sb, this.spec16], Math.ceil(this.W / 16), Math.ceil(this.NY / 16), pairs);
        this.device.queue.submit([enc.finish()]);
        for (const b of [clr, eb, sct, sb, sp, ...temps]) b.destroy();
      }
    }

    // The images of every job channel (Float32Array cw * ch each).
    async images(job) {
      if (this.lost) throw new Error(this.lost);
      const geo = `${job.geometry}:${job.NX}x${job.NY}:${job.nx}x${job.ny}`;
      if (geo !== this.geometry) this.reset(job);
      this.ensureKernels(job);
      const needed = new Set();
      for (const ch of job.channels) for (const d of ch) needed.add(d.key);
      this.ensurePlanes(job, needed);
      const nChan = job.channels.length;
      if (!nChan) return [];
      // Re-pairing: every channel's spectrum.
      let nd = 0;
      for (const ch of job.channels) nd += ch.length;
      const depI = new Uint32Array(4 * Math.max(1, nd)), depW = new Float32Array(2 * Math.max(1, nd)), chans = new Uint32Array(2 * nChan);
      let d = 0;
      job.channels.forEach((ch, c) => {
        chans[2 * c] = d; chans[2 * c + 1] = ch.length;
        for (const e of ch) {
          const pl = this.planes.get(e.key);
          depI[4 * d] = pl.slot; depI[4 * d + 1] = this.kernels.get(e.p0);
          depI[4 * d + 2] = e.two ? this.kernels.get(e.p1) : NONE; depI[4 * d + 3] = f32bits(pl.scale);
          depW[2 * d] = e.w0; depW[2 * d + 1] = e.w1;
          d++;
        }
      });
      const temps = [];
      const enc = this.device.createCommandEncoder();
      const chanSpec = this.storage(nChan * this.SS * 8);
      const bI = this.upload(depI), bW = this.upload(depW), bC = this.upload(chans);
      const [mx, my, ml] = this.grid256(this.SS);
      const mp = this.uniform([this.SS, nChan, ml, 0]);
      this.dispatch(enc, 'wf_mac', [mp, this.spec16, this.kspec, bI, bW, bC, chanSpec], mx, my, nChan);
      temps.push(chanSpec, bI, bW, bC, mp);
      // Pairs of channels -> grids -> inverse FFT -> FOV images.
      const cs = job.cw * job.ch, imgs = this.storage(nChan * cs * 4);
      temps.push(imgs);
      const pairList = [];
      for (let c = 0; c < nChan; c += 2) pairList.push([c, c + 1 < nChan ? c + 1 : NONE]);
      for (let p0 = 0; p0 < pairList.length; p0 += this.pairCap) {
        const part = pairList.slice(p0, p0 + this.pairCap), pairs = part.length;
        const pb = this.upload(new Uint32Array(part.flat()));
        const ex = new Uint32Array([this.NX, this.NY, this.W, this.SS, this.PS, pairs, f32bits(job.fracX), f32bits(job.fracY)]);
        const eu = this.uniform(ex);
        this.dispatch(enc, 'wf_expand', [eu, chanSpec, pb, this.work], Math.ceil(this.NX / 16), Math.ceil(this.NY / 16), pairs);
        this.fft2(enc, pairs, 1, temps);
        const cu = this.uniform([this.NX, this.PS, job.fovX0, job.fovY0, job.cw, job.ch, f32bits(1 / (this.NX * this.NY)), 0]);
        this.dispatch(enc, 'wf_crop', [cu, this.work, pb, imgs], Math.ceil(job.cw / 16), Math.ceil(job.ch / 16), pairs);
        temps.push(pb, eu, cu);
      }
      const rb = this.buffer(nChan * cs * 4, GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST);
      enc.copyBufferToBuffer(imgs, 0, rb, 0, nChan * cs * 4);
      this.device.queue.submit([enc.finish()]);
      await rb.mapAsync(GPUMapMode.READ);
      const all = new Float32Array(rb.getMappedRange().slice(0));
      rb.unmap();
      rb.destroy();
      for (const b of temps) b.destroy();
      if (this.lost) throw new Error(this.lost);
      const out = [];
      for (let c = 0; c < nChan; c++) out.push(all.subarray(c * cs, (c + 1) * cs));
      return out;
    }
  }

  // The job of WASM WideField session h (isc_wf_job), copied out of the heap.
  function jobFromModule(M, h) {
    const info = M._malloc(14 * 4), frac = M._malloc(16);
    try {
      if (M._isc_wf_job(h, info, frac) !== 0) return null;
      const I = M.HEAP32.slice(info / 4, info / 4 + 14), F = M.HEAPF64.slice(frac / 8, frac / 8 + 2);
      const job = { NX: I[0], NY: I[1], nx: I[2], ny: I[3], fovX0: I[4], fovY0: I[5], cw: I[6], ch: I[7],
        hasPersistent: !!I[11], dyes: I[12], geometry: I[13], fracX: F[0], fracY: F[1], kernels: [], planes: [], channels: [] };
      const SS = (job.NX / 2 + 1) * job.NY;
      const tmp = M._malloc(16);
      for (let i = 0; i < I[8]; i++) {
        const ptr = M._isc_wf_kernel(h, i, tmp);
        job.kernels.push({ p: M.HEAP32[tmp / 4], spec: M.HEAPF32.slice(ptr / 4, ptr / 4 + 2 * SS) });
      }
      for (let i = 0; i < I[9]; i++) {
        const cp = M._isc_wf_plane(h, i, tmp, tmp + 12);
        const n = M.HEAP32[tmp / 4], key = `${M.HEAPU32[tmp / 4 + 1]}:${M.HEAPU32[tmp / 4 + 2]}`, abs = M.HEAPF32[tmp / 4 + 3];
        const vp = M._isc_wf_plane_values(h, i);
        job.planes.push({ key, absSum: abs, cells: M.HEAPU32.slice(cp / 4, cp / 4 + n), values: M.HEAPF32.slice(vp / 4, vp / 4 + n) });
      }
      for (let c = 0; c < I[10]; c++) {
        const dp = M._isc_wf_channel(h, c, tmp), n = M.HEAP32[tmp / 4];
        const D = M.HEAP32.slice(dp / 4, dp / 4 + 7 * n), Dw = new Float32Array(D.buffer);
        const deps = [];
        for (let k = 0; k < n; k++)
          deps.push({ key: `${D[7 * k] >>> 0}:${D[7 * k + 1] >>> 0}`, p0: D[7 * k + 2], p1: D[7 * k + 3], two: !!D[7 * k + 4],
            w0: Dw[7 * k + 5], w1: Dw[7 * k + 6] });
        job.channels.push(deps);
      }
      M._free(tmp);
      return job;
    } finally {
      M._free(info); M._free(frac);
    }
  }

  self.IscWfGpu = { create: (wgsl, allowFallback) => Host.create(wgsl, allowFallback), jobFromModule, kernelSources };
}
self.iscWfGpuDefine = iscWfGpuDefine;
iscWfGpuDefine();
